routes/web.php
<?php

use App\Http\Controllers\DiscountController;

// auth
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
// todo: GET request to 'logout' route causes MethodNotAllowedHttpException
// Search for "POST to Logout" - https://laravel.com/docs/5.3/upgrade

// password reset
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');


Route::middleware(['auth:web'])->group(function () {

    Route::get('/', function () {
        return view('home');
    });

    Route::get('supplies/{supply}/catalog_imports', 'CatalogImportController@index')->name('catalog_imports.index');
    Route::post('supplies/{supply}/catalog_imports/upload', 'CatalogImportController@upload')->name('catalog_imports.upload');
    Route::get('supplies/{supply}/catalog_imports/preview/{import}', 'CatalogImportController@preview')->name('catalog_imports.preview');
    Route::post('supplies/{supply}/catalog_imports/apply/{import}', 'CatalogImportController@apply')->name('catalog_imports.apply');
    Route::delete('supplies/{supply}/catalog_imports/{import}', 'CatalogImportController@destroy')->name('catalog_imports.destroy');

    Route::get('supplies/{supply}/discounts', 'DiscountController@index')->name('discounts.index');
    Route::get('supplies/{supply}/discounts/export', [DiscountController::class, 'export'])->name('discounts.export');
    Route::post('supplies/{supply}/discounts/upload', [DiscountController::class, 'upload'])->name('discounts.upload');
    Route::get('supplies/{supply}/discounts/preview', [DiscountController::class, 'preview'])->name('discounts.preview');
    Route::post('supplies/{supply}/discounts/apply', [DiscountController::class, 'apply'])->name('discounts.apply');
    Route::patch('supplies/{supply}/discounts/{discount}', 'DiscountController@update')->name('discounts.update');
    Route::delete('supplies/{supply}/discounts/{discount}', 'DiscountController@destroy')->name('discounts.destroy');

    Route::resources([
        'admins' => 'AdminController',
        'manufacturers' => 'ManufacturerController',
        'suppliers' => 'SupplierController',
        'supplies' => 'SupplyController',
        'parts' => 'PartController',
        'imps' => 'ImpController',
        'humans' => 'HumanController',
        'minions' => 'MinionController',
    ]);
});

resources/views/admins/create.blade.php
@extends('layouts.common')

@section('title', __('admins.create_heading'))

@section('heading', __('admins.create_heading'))

@section('main')

    @include('layouts.notification')

    <form method="POST" action="{{ route('admins.store') }}">

        @csrf

        <text-input
                label="@lang('admins.name')"
                id="name"
                value="{{ old('name') }}"
                color="{{ $errors->has('name') ? 'is-danger' : '' }}"
        >
        </text-input>

        <dropdown
                label="@lang('admins.role')"
                id="role"
                :options='@json($roles)'
                :preselected="{{ old('role') ?: $preselected }}"
        >
        </dropdown>

        <text-input
                label="@lang('admins.note')"
                id="note"
                value="{{ old('note') }}"
                color="{{ $errors->has('note') ? 'is-danger' : '' }}"
        >
        </text-input>

        <text-input
                label="@lang('admins.email')"
                id="email"
                value="{{ old('email') }}"
                color="{{ $errors->has('email') ? 'is-danger' : '' }}"
        >
        </text-input>

        <br>
        <button-submit
                id="submit"
                title="@lang('general.create_btn')"
                color="is-primary"
                cancel-href="{{ route('admins.index') }}"
                cancel-title="@lang('general.cancel_btn')"
        >
        </button-submit>

    </form>

@endsection

resources/views/admins/edit.blade.php
@extends('layouts.common')

@section('title', __('admins.edit_heading', ['name' => $admin->name]))

@section('heading', __('admins.edit_heading', ['name' => $admin->name]))

@section('main')

    @include('layouts.notification')

    <form method="POST" action="{{ route('admins.update', ['admin' => $admin->id]) }}">

        @csrf
        @method('PATCH')

        <text-input
                label="@lang('admins.name')"
                id="name"
                value="{{ old('name') ?: $admin->name }}"
                color="{{ $errors->has('name') ? 'is-danger' : '' }}"
        >
        </text-input>

        <dropdown
                label="@lang('admins.role')"
                id="role"
                :options='@json($roles)'
                :preselected="{{ old('role') ?: $admin->role }}"
        >
        </dropdown>

        <text-input
                label="@lang('admins.note')"
                id="note"
                value="{{ old('note') ?: $admin->note }}"
                color="{{ $errors->has('note') ? 'is-danger' : '' }}"
        >
        </text-input>

        <text-input
                label="@lang('admins.email')"
                id="email"
                value="{{ old('email') ?: $admin->email }}"
                color="{{ $errors->has('email') ? 'is-danger' : '' }}"
        >
        </text-input>

        <br>
        <button-submit
                id="submit"
                title="@lang('general.save_btn')"
                color="is-primary"
                cancel-href="{{ route('admins.index') }}"
                cancel-title="@lang('general.cancel_btn')"
        >
        </button-submit>

    </form>

    <br>
    @include('components.delete_button', [
        'route' => 'admins.destroy',
        'params' => [
            'id' => $admin->id
        ]
    ])

@endsection

resources/views/admins/index.blade.php
@extends('layouts.common')

@section('title', __('admins.index_heading'))

@section('heading', __('admins.index_heading'))

@section('main')

    @include('layouts.notification')

    <table class="table is-bordered is-striped">
        <thead>
        <tr>
            <th></th>
            <th>@lang('admins.name')</th>
            <th>@lang('admins.role')</th>
            <th>@lang('admins.note')</th>
            <th>@lang('admins.email')</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($admins as $key => $admin)
            <tr>
                <td>{{ $key + 1 }}</td>
                <td>
                    {{ $admin->name }}
                </td>
                <td class="has-text-centered">
                    @if (Autocarat\Core\Admin::ROLE_ADMIN === $admin->role)
                        <fa icon="star"></fa>
                    @endif
                </td>
                <td>{{ $admin->note }}</td>
                <td>{{ $admin->email }}</td>
                <td>
                    <a href="{{ route('admins.edit', ['admin' => $admin->id]) }}">
                        <fa icon="cog"></fa>
                    </a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    @if (
        Auth::check() &&
        Auth::user()->can('create', \Autocarat\Core\Admin::class)
    )
        <button-link
                color="is-primary"
                href="{{ route('admins.create') }}"
                title="@lang('general.add_btn')"
        >
        </button-link>
    @endif

@endsection